### ISSUE TITLE
FRb. Creation of Account

### ISSUE THREAD

**Issue by kcgalee** [WSU-4110/LOST#2]
| FRb. Creation of Account |
|---|
|**Goal**:  User account is created |
**Stakeholders:** Users |
| **Description:**  LOST account is created through the authorization of Spotify |
| **Origin:** Based on initial project specification   document, team 
members came up with this description during the first   meeting.|
| **Version:** 1.0  |
|**Date:** 02/12/2022|
|  **Priority:** 1 |

**Comment by kelbel272** [comment]
User can authorize their Spotify account when clicking Login from the Login Page
