### ISSUE TITLE
NFR5d. User searches for a song or attribute that does not exis

### ISSUE THREAD

**Issue by kcgalee** [WSU-4110/LOST#22]
|NFR5d. User searches for a song or attribute that does not exist|
|---|
|Goal: Response to user if song or attribute does not exist.
Stakeholders: Users |
| Description: The search page will show “This *song or attribute* does not exist”. |
| Origin: Based on initial project document, team members came up with this description during the first meeting. |
| Version: 1.0  |
|Date: 02/12/2022 |
|  Priority: 2 |

**Comment by cristinanoelle11** [comment]
on the song page if the user doesn't see an attribute they like from the basic ones given they can add their own attributes and it will save in our database. If the user searches for a song that does not exist then the api will suggest 5 other songs similar that are available on Spotify
