### ISSUE TITLE
FRe. User call to generate playlist

### ISSUE THREAD

**Issue by kcgalee** [WSU-4110/LOST#5]
|FRe. User call to generate playlist|
|---|
|Goal: The user is able to generate playlist
Stakeholders: Users |
| Description: After tagging a song(s) with an attribute, the application prompts the user to call to generate a playlist that algorithmically displays songs based on the user’s preferences. |
| Origin: Based on initial project document, team members came up with this description during the first meeting. |
| Version: 1.0  |
|Date: 02/12/2022|
|  Priority: 2 |

**Comment by kelbel272** [comment]
After logging in, on Home.js user can click on an Attribute and a playlist for that attribute will be generated on the page & in Spotify and automatically added into their account
