### ISSUE TITLE
FRf. Application generates playlist

### ISSUE THREAD

**Issue by kcgalee** [WSU-4110/LOST#6]
|FRf. Application generates playlist|
|---|
|Goal: The system creates the playlist for the user
Stakeholders: Users |
| Description: The application algorithmically displays songs based on the user’s preferences. |
| Origin: Based on initial project document, team members came up with this description during the first meeting. |
| Version: 1.0  |
|Date: 02/12/2022 |
|  Priority: 1 |

**Comment by kelbel272** [comment]
LOST creates a playlist in user's Spotify and adds songs w/ that attribute
