### ISSUE TITLE
FRg. User can add attributes to songs while listening

### ISSUE THREAD

**Issue by kcgalee** [WSU-4110/LOST#7]
|FRg. User can add attributes to songs while listening|
|---|
|Goal: User can add attributes to songs while listening to music on the application
Stakeholders: Users |
| Description: A drop down/pull down feature will show an attributes page behind the music player to tag attributes. |
| Origin: Based on initial project document, team members came up with this description during the first meeting. |
| Version: 1.0  |
|Date: 02/12/2022 |
|  Priority: 2 |

**Comment by cristinanoelle11** [comment]
user can do this on the song page!
